services:

  pixivutil-matrix-notifications:
    build: .
    container_name: pixivutil-matrix-notifications
    command: uvicorn PixivServer.notifier:app --host 0.0.0.0 --log-level info
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro # comment out if not using self-signed certificate/ca is somewhere else
    environment:
      - REQUESTS_CA_BUNDLE=$REQUESTS_CA_BUNDLE # comment out if not using self-signed certificate/ca is somewhere else
      - MATRIX_HOST=$MATRIX_HOST
      - MATRIX_ACCESS_TOKEN=$MATRIX_ACCESS_TOKEN
      - MATRIX_ROOM=$MATRIX_ROOM
    depends_on:
      - rabbitmq
    env_file:
      - .env

  pixivutil-worker:
    depends_on:
      - pixivutil-matrix-notifications
    env_file:
      - .env

  pixivutil-server:
    depends_on:
      - pixivutil-matrix-notifications
    env_file:
      - .env